ROSTER = [{"id":"29315","photo":"029315.jpg","name":"KILGORE, DEAN","race":"BLACK","sex":"MALE","dob":"2/12/71","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"11225","photo":"011225.jpg","name":"ROSE, JAMES F","race":"WHITE","sex":"MALE","dob":"10/14/71","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"8035","photo":"008035.jpg","name":"PHILLIPS, HARRY F","race":"BLACK","sex":"MALE","dob":"4/30/74","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"49546","photo":"049546.jpg","name":"FOSTER, CHARLES K","race":"WHITE","sex":"MALE","dob":"10/7/75","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"53948","photo":"053948.jpg","name":"ZEIGLER, WILLIAM T","race":"WHITE","sex":"MALE","dob":"7/19/76","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"56338","photo":"056338.jpg","name":"SIRECI, HENRY P JR","race":"WHITE","sex":"MALE","dob":"11/16/76","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"58279","photo":"058279.jpg","name":"LUCAS, HAROLD G","race":"WHITE","sex":"MALE","dob":"2/10/77","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"58293","photo":"058293.jpg","name":"HITCHCOCK, JAMES E","race":"WHITE","sex":"MALE","dob":"2/14/77","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"53779","photo":"053779.jpg","name":"THOMPSON, WILLIAM L","race":"WHITE","sex":"MALE","dob":"1/26/78","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"63143","photo":"063143.jpg","name":"DOWNS, ERNEST C","race":"WHITE","sex":"MALE","dob":"1/27/78","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"44049","photo":"044049.jpg","name":"BOOKER, STEPHEN T","race":"BLACK","sex":"MALE","dob":"10/2/78","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"67048","photo":"067048.jpg","name":"WHITE, WILLIAM M","race":"WHITE","sex":"MALE","dob":"12/22/78","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"68610","photo":"068610.jpg","name":"DILLBECK, DONALD D","race":"WHITE","sex":"MALE","dob":"6/13/79","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"71615","photo":"071615.jpg","name":"SCOTT, PAUL W","race":"WHITE","sex":"MALE","dob":"1/7/80","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"73045","photo":"073045.jpg","name":"JENNINGS, BRYAN F","race":"WHITE","sex":"MALE","dob":"5/8/80","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"72847","photo":"072847.jpg","name":"JACKSON, ETHERIA V","race":"BLACK","sex":"MALE","dob":"7/10/80","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"75812","photo":"075812.jpg","name":"QUINCE, KENNETH D","race":"BLACK","sex":"MALE","dob":"10/21/80","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"322534","photo":"322534.jpg","name":"ROBERTSON, JAMES","race":"WHITE","sex":"MALE","dob":"11/26/80","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"51769","photo":"051769.jpg","name":"OATS, SONNY B JR","race":"BLACK","sex":"MALE","dob":"2/10/81","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"78081","photo":"078081.jpg","name":"LIGHTBOURN, IAN","race":"BLACK","sex":"MALE","dob":"5/1/81","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"81163","photo":"081163.jpg","name":"PETERSON, CHARLES","race":"BLACK","sex":"MALE","dob":"12/10/81","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"81792","photo":"081792.jpg","name":"CARD, JAMES A SR","race":"WHITE","sex":"MALE","dob":"2/1/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"82284","photo":"082284.jpg","name":"HERRING, TED","race":"BLACK","sex":"MALE","dob":"3/1/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"83040","photo":"083040.jpg","name":"POPE, THOMAS D","race":"WHITE","sex":"MALE","dob":"4/9/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"84582","photo":"084582.jpg","name":"BLANCO, OMAR","race":"WHITE","sex":"MALE","dob":"6/23/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"84643","photo":"084643.jpg","name":"PACE, BRUCE D","race":"BLACK","sex":"MALE","dob":"6/28/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"85488","photo":"085488.jpg","name":"BYRD, MILFORD W","race":"WHITE","sex":"MALE","dob":"8/18/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"86006","photo":"086006.jpg","name":"DOYLE, DANIEL L","race":"WHITE","sex":"MALE","dob":"9/22/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"87429","photo":"087429.jpg","name":"CAVE, ALPHONSO","race":"BLACK","sex":"MALE","dob":"12/17/82","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"789049","photo":"789049.jpg","name":"PARKER, J. B","race":"BLACK","sex":"MALE","dob":"1/12/83","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"88568","photo":"088568.jpg","name":"BATES, KAYLE B","race":"BLACK","sex":"MALE","dob":"3/14/83","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"90411","photo":"090411.jpg","name":"ROSE, MILO A","race":"WHITE","sex":"MALE","dob":"7/14/83","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"749768","photo":"749768.jpg","name":"WRIGHT, JOEL D","race":"WHITE","sex":"MALE","dob":"9/23/83","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"490606","photo":"490606.jpg","name":"SMITH, DERRICK T","race":"BLACK","sex":"MALE","dob":"12/2/83","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"93094","photo":"093094.jpg","name":"PEEDE, ROBERT I","race":"WHITE","sex":"MALE","dob":"3/7/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"93268","photo":"093268.jpg","name":"WALTON, JASON D","race":"WHITE","sex":"MALE","dob":"3/22/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"482053","photo":"482053.jpg","name":"LAMBRIX, MICHAEL R","race":"WHITE","sex":"MALE","dob":"3/23/84","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"93417","photo":"093417.jpg","name":"KELLEY, WILLIAM","race":"WHITE","sex":"MALE","dob":"4/6/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"716927","photo":"716927.jpg","name":"PUIATTI, CARL","race":"WHITE","sex":"MALE","dob":"5/14/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"94506","photo":"094506.jpg","name":"MUEHLEMAN, JEFFREY A","race":"WHITE","sex":"MALE","dob":"7/17/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"72002","photo":"072002.jpg","name":"KOKAL, GREGORY A","race":"WHITE","sex":"MALE","dob":"11/14/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"648711","photo":"648711.jpg","name":"MCKENZIE, NORMAN B","race":"WHITE","sex":"MALE","dob":"11/27/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"910610","photo":"910610.jpg","name":"NIXON, JOE E","race":"BLACK","sex":"MALE","dob":"11/30/84","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"494041","photo":"494041.jpg","name":"LONG, ROBERT J","race":"WHITE","sex":"MALE","dob":"5/21/85","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"99269","photo":"099269.jpg","name":"RHODES, RICHARD W","race":"WHITE","sex":"MALE","dob":"9/17/85","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"101660","photo":"101660.jpg","name":"OWEN, DUANE E","race":"WHITE","sex":"MALE","dob":"3/19/86","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"73053","photo":"073053.jpg","name":"HARDWICK, JOHN G JR","race":"WHITE","sex":"MALE","dob":"4/24/86","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"648254","photo":"648254.jpg","name":"MARSHALL, MATTHEW","race":"BLACK","sex":"MALE","dob":"5/20/86","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"73283","photo":"073283.jpg","name":"RODRIGUEZ, MANOLO","race":"HISPANIC","sex":"MALE","dob":"5/27/86","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"102992","photo":"102992.jpg","name":"HARVEY, HAROLD L JR.","race":"WHITE","sex":"MALE","dob":"6/23/86","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"479774","photo":"479774.jpg","name":"STEWART, KENNETH A","race":"WHITE","sex":"MALE","dob":"10/8/86","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"105661","photo":"105661.jpg","name":"REED, GROVER B","race":"WHITE","sex":"MALE","dob":"1/9/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"92501","photo":"092501.jpg","name":"BARWICK, DARRYL","race":"WHITE","sex":"MALE","dob":"1/30/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"106014","photo":"106014.jpg","name":"DAVIS, MARK A","race":"WHITE","sex":"MALE","dob":"2/3/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"19762","photo":"019762.jpg","name":"BROWN, PAUL A","race":"WHITE","sex":"MALE","dob":"3/5/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"640779","photo":"640779.jpg","name":"RIVERA, MICHAEL T","race":"WHITE","sex":"MALE","dob":"5/8/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"573461","photo":"573461.jpg","name":"TROTTER, MELVIN","race":"BLACK","sex":"MALE","dob":"6/18/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"108509","photo":"108509.jpg","name":"DAILEY, JAMES","race":"WHITE","sex":"MALE","dob":"8/10/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"40002","photo":"040002.jpg","name":"REAVES, WILLIAM","race":"BLACK","sex":"MALE","dob":"9/2/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"21641","photo":"021641.jpg","name":"CHERRY, ROGER L","race":"BLACK","sex":"MALE","dob":"9/26/87","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"226426","photo":"226426.jpg","name":"OCCHICONE, DOMINICK","race":"WHITE","sex":"MALE","dob":"11/10/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"639131","photo":"639131.jpg","name":"SOCHOR, DENNIS","race":"WHITE","sex":"MALE","dob":"11/16/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"72746","photo":"072746.jpg","name":"FREEMAN, JOHN D","race":"WHITE","sex":"MALE","dob":"12/14/87","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"42115","photo":"042115.jpg","name":"ANDERSON, RICHARD H","race":"WHITE","sex":"MALE","dob":"2/29/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"46651","photo":"046651.jpg","name":"HALIBURTON, JERRY","race":"BLACK","sex":"MALE","dob":"4/19/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"111508","photo":"111508.jpg","name":"JONES, RANDALL","race":"WHITE","sex":"MALE","dob":"5/4/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"111918","photo":"111918.jpg","name":"BURNS, DANIEL  JR.","race":"BLACK","sex":"MALE","dob":"6/7/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"112232","photo":"112232.jpg","name":"DUCKETT, JAMES A","race":"WHITE","sex":"MALE","dob":"6/30/88","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"97494","photo":"097494.jpg","name":"DERRICK, SAMUEL J","race":"WHITE","sex":"MALE","dob":"7/25/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"112850","photo":"112850.jpg","name":"WALLS, FRANK A","race":"WHITE","sex":"MALE","dob":"8/24/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"112967","photo":"112967.jpg","name":"PONTICELLI, ANTHONY J","race":"WHITE","sex":"MALE","dob":"9/6/88","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"78387","photo":"078387.jpg","name":"ASAY, MARK J","race":"WHITE","sex":"MALE","dob":"11/18/88","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"115769","photo":"115769.jpg","name":"RANDOLPH, RICHARD B","race":"BLACK","sex":"MALE","dob":"4/5/89","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"86160","photo":"086160.jpg","name":"TAYLOR, PERRY A","race":"BLACK","sex":"MALE","dob":"5/15/89","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"116320","photo":"116320.jpg","name":"SHERE, RICHARD E JR.","race":"WHITE","sex":"MALE","dob":"5/18/89","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"99752","photo":"099752.jpg","name":"MCCOY, RICHARD L","race":"BLACK","sex":"MALE","dob":"6/8/89","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"117157","photo":"117157.jpg","name":"HODGES, GEORGE M","race":"WHITE","sex":"MALE","dob":"8/11/89","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"286020","photo":"286020.jpg","name":"WATTS, TONY R","race":"BLACK","sex":"MALE","dob":"9/15/89","entry":"LAKE C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"96867","photo":"096867.jpg","name":"PIETRI, NOBERTO","race":"HISPANIC","sex":"MALE","dob":"3/30/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"119682","photo":"119682.jpg","name":"VALENTINE, TERANCE","race":"BLACK","sex":"MALE","dob":"4/16/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"119773","photo":"119773.jpg","name":"PETERKA, DANIEL J","race":"WHITE","sex":"MALE","dob":"4/25/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"394141","photo":"394141.jpg","name":"RODRIGUEZ, JUAN D","race":"HISPANIC","sex":"MALE","dob":"6/12/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"188854","photo":"188854.jpg","name":"COX, ALLEN W","race":"WHITE","sex":"MALE","dob":"6/20/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"120467","photo":"120467.jpg","name":"ATWATER, JEFFREY","race":"WHITE","sex":"MALE","dob":"7/10/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"751166","photo":"751166.jpg","name":"GASKIN, LOUIS B","race":"BLACK","sex":"MALE","dob":"7/19/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"256512","photo":"256512.jpg","name":"DEPARVINE, WILLIAM J","race":"WHITE","sex":"MALE","dob":"9/13/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"729185","photo":"729185.jpg","name":"GERALDS, MARK","race":"WHITE","sex":"MALE","dob":"9/14/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"616550","photo":"616550.jpg","name":"FOTOPOULOS, KONSTANTIN O","race":"WHITE","sex":"MALE","dob":"11/1/90","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"65145","photo":"065145.jpg","name":"HEATH, RONALD P","race":"WHITE","sex":"MALE","dob":"12/17/90","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"324342","photo":"324342.jpg","name":"GUARDADO, JESSE","race":"WHITE","sex":"MALE","dob":"2/15/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"39763","photo":"039763.jpg","name":"LAWRENCE, GARY","race":"WHITE","sex":"MALE","dob":"2/21/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"812974","photo":"812974.jpg","name":"CLARK, RONALD","race":"WHITE","sex":"MALE","dob":"2/22/91","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"121965","photo":"121965.jpg","name":"TREPAL, GEORGE J","race":"WHITE","sex":"MALE","dob":"3/8/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"122079","photo":"122079.jpg","name":"ARBELAEZ, GUILLERMO O","race":"HISPANIC","sex":"MALE","dob":"4/2/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"182543","photo":"182543.jpg","name":"GRIFFIN, MICHAEL A","race":"WHITE","sex":"MALE","dob":"4/25/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"351997","photo":"351997.jpg","name":"PITTMAN, DAVID J","race":"WHITE","sex":"MALE","dob":"4/26/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"699349","photo":"699349.jpg","name":"LOWE, RODNEY T","race":"BLACK","sex":"MALE","dob":"5/14/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"693504","photo":"693504.jpg","name":"ARMSTRONG, LANCELOT U","race":"BLACK","sex":"MALE","dob":"7/2/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"122551","photo":"122551.jpg","name":"STEIN, STEVEN E","race":"WHITE","sex":"MALE","dob":"7/23/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"500914","photo":"500914.jpg","name":"HANNON, PATRICK C","race":"WHITE","sex":"MALE","dob":"8/14/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"100063","photo":"100063.jpg","name":"SWEET, WILLIAM E","race":"BLACK","sex":"MALE","dob":"8/30/91","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"338043","photo":"338043.jpg","name":"JOHNSON, EMANUEL","race":"BLACK","sex":"MALE","dob":"9/10/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"649748","photo":"649748.jpg","name":"RIMMER, ROBERT","race":"BLACK","sex":"MALE","dob":"9/24/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"216728","photo":"216728.jpg","name":"ARCHER, ROBIN L","race":"WHITE","sex":"MALE","dob":"9/25/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"138315","photo":"138315.jpg","name":"KEARSE, BILLY L","race":"BLACK","sex":"MALE","dob":"11/8/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"288322","photo":"288322.jpg","name":"MUNGIN, ANTHONY","race":"BLACK","sex":"MALE","dob":"11/27/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"288500","photo":"288500.jpg","name":"TAYLOR, STEVEN R","race":"WHITE","sex":"MALE","dob":"12/9/91","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"707742","photo":"707742.jpg","name":"WILLACY, CHADWICK","race":"BLACK","sex":"MALE","dob":"12/13/91","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"335421","photo":"335421.jpg","name":"COLE, LORAN K","race":"WHITE","sex":"MALE","dob":"2/24/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"217358","photo":"217358.jpg","name":"MELTON, ANTONIO L","race":"BLACK","sex":"MALE","dob":"5/27/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"721842","photo":"721842.jpg","name":"KRAWCZUK, ANTON","race":"WHITE","sex":"MALE","dob":"5/28/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"71551","photo":"071551.jpg","name":"BARNES, JAMES P","race":"WHITE","sex":"MALE","dob":"7/1/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"220267","photo":"220267.jpg","name":"SUGGS, ERNEST D","race":"WHITE","sex":"MALE","dob":"7/15/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"440701","photo":"440701.jpg","name":"JOHNSON, RONNIE","race":"BLACK","sex":"MALE","dob":"8/4/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"936283","photo":"936283.jpg","name":"WHITTON, GARY R","race":"WHITE","sex":"MALE","dob":"9/10/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"62368","photo":"062368.jpg","name":"JONES, HARRY","race":"BLACK","sex":"MALE","dob":"11/20/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"368527","photo":"368527.jpg","name":"WINDOM, CURTIS","race":"BLACK","sex":"MALE","dob":"11/23/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"490989","photo":"490989.jpg","name":"FENNIE, ALFRED L","race":"BLACK","sex":"MALE","dob":"12/2/92","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"516349","photo":"516349.jpg","name":"FINNEY, CHARLES W","race":"BLACK","sex":"MALE","dob":"12/2/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"684135","photo":"684135.jpg","name":"FARINA, ANTHONY J","race":"WHITE","sex":"MALE","dob":"12/16/92","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"321031","photo":"321031.jpg","name":"SPENCER, DUSTY R","race":"WHITE","sex":"MALE","dob":"1/4/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"122995","photo":"122995.jpg","name":"MARQUARD, JOHN C","race":"WHITE","sex":"MALE","dob":"2/5/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"110365","photo":"110365.jpg","name":"BOGLE, BRETT A","race":"WHITE","sex":"MALE","dob":"2/24/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"120190","photo":"120190.jpg","name":"CUMMING-EL, F W","race":"BLACK","sex":"MALE","dob":"3/3/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"726848","photo":"726848.jpg","name":"ORME, RODERICK M","race":"WHITE","sex":"MALE","dob":"3/30/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"713735","photo":"713735.jpg","name":"ROBINSON, MICHAEL L","race":"WHITE","sex":"MALE","dob":"4/19/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"420481","photo":"420481.jpg","name":"JONES, VICTOR T","race":"BLACK","sex":"MALE","dob":"6/2/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123069","photo":"123069.jpg","name":"REESE, JOHN L","race":"BLACK","sex":"MALE","dob":"6/25/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123096","photo":"123096.jpg","name":"GAMBLE, GUY R","race":"WHITE","sex":"MALE","dob":"8/11/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"115624","photo":"115624.jpg","name":"HUNTER, JAMES E","race":"BLACK","sex":"MALE","dob":"8/18/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"268130","photo":"268130.jpg","name":"FRANKLIN, QUAWN M","race":"BLACK","sex":"MALE","dob":"9/28/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"189262","photo":"189262.jpg","name":"SMITH, STEPHEN","race":"WHITE","sex":"MALE","dob":"11/2/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"941687","photo":"941687.jpg","name":"CONSALVO, ROBERT A","race":"WHITE","sex":"MALE","dob":"11/19/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"318987","photo":"318987.jpg","name":"HARTLEY, KENNETH","race":"BLACK","sex":"MALE","dob":"12/9/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"118167","photo":"118167.jpg","name":"MERCK, TROY  JR.","race":"WHITE","sex":"MALE","dob":"12/10/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"116335","photo":"116335.jpg","name":"MOORE, THOMAS J","race":"BLACK","sex":"MALE","dob":"12/16/93","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"65135","photo":"065135.jpg","name":"ISRAEL, CONNIE R","race":"BLACK","sex":"MALE","dob":"2/2/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"905288","photo":"905288.jpg","name":"SLINEY, JACK R","race":"WHITE","sex":"MALE","dob":"2/21/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"330290","photo":"330290.jpg","name":"EVANS, STEVEN M","race":"BLACK","sex":"MALE","dob":"3/18/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"309066","photo":"309066.jpg","name":"MORTON, ALVIN","race":"WHITE","sex":"MALE","dob":"3/21/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"214353","photo":"214353.jpg","name":"HALL, ENOCH D","race":"BLACK","sex":"MALE","dob":"4/1/94","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"447891","photo":"447891.jpg","name":"ANDERSON, CHARLES L","race":"BLACK","sex":"MALE","dob":"4/19/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"313067","photo":"313067.jpg","name":"BRANCH, ERIC S","race":"WHITE","sex":"MALE","dob":"5/5/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"309567","photo":"309567.jpg","name":"JONES, MARVIN B","race":"BLACK","sex":"MALE","dob":"5/31/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"48606","photo":"048606.jpg","name":"WILLIAMSON, DANA","race":"WHITE","sex":"MALE","dob":"7/21/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"311509","photo":"311509.jpg","name":"THOMAS, WILLIAM G","race":"WHITE","sex":"MALE","dob":"7/22/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"310094","photo":"310094.jpg","name":"FOSTER, JERMAINE A","race":"BLACK","sex":"MALE","dob":"8/26/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123763","photo":"123763.jpg","name":"GONZALEZ, RICARDO","race":"HISPANIC","sex":"MALE","dob":"10/18/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"445903","photo":"445903.jpg","name":"FRANQUI, LEONARDO","race":"WHITE","sex":"MALE","dob":"10/18/94","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"445904","photo":"445904.jpg","name":"SAN MARTIN, PABLO","race":"WHITE","sex":"MALE","dob":"10/18/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"962032","photo":"962032.jpg","name":"HOSKINS, JOHNNY","race":"BLACK","sex":"MALE","dob":"11/4/94","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"61360","photo":"061360.jpg","name":"DAMREN, FLOYD W","race":"WHITE","sex":"MALE","dob":"6/7/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123846","photo":"123846.jpg","name":"HAMILTON, RICHARD E","race":"WHITE","sex":"MALE","dob":"6/12/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123847","photo":"123847.jpg","name":"WAINWRIGHT, ANTHONY F","race":"WHITE","sex":"MALE","dob":"6/12/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"379799","photo":"379799.jpg","name":"GUDINAS, THOMAS L","race":"WHITE","sex":"MALE","dob":"6/19/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"26985","photo":"026985.jpg","name":"LOTT, KEN E","race":"WHITE","sex":"MALE","dob":"7/7/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"300807","photo":"300807.jpg","name":"DAVIS, TONEY D","race":"BLACK","sex":"MALE","dob":"7/18/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"450307","photo":"450307.jpg","name":"MENDOZA, MARBEL","race":"WHITE","sex":"MALE","dob":"8/3/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"969121","photo":"969121.jpg","name":"JAMES, EDWARD T","race":"WHITE","sex":"MALE","dob":"8/18/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"302491","photo":"302491.jpg","name":"SHELLITO, MICHAEL","race":"HISPANIC","sex":"MALE","dob":"10/23/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"764970","photo":"764970.jpg","name":"WHITFIELD, ERNEST","race":"BLACK","sex":"MALE","dob":"10/24/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123911","photo":"180399.jpg","name":"GORDON, ROBERT R","race":"BLACK","sex":"MALE","dob":"11/17/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"180399","photo":"123911.jpg","name":"MCDONALD, MERYL S","race":"BLACK","sex":"MALE","dob":"11/17/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"610979","photo":"610979.jpg","name":"KNIGHT, RONALD","race":"WHITE","sex":"MALE","dob":"12/21/95","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124052","photo":"124052.jpg","name":"RALEIGH, BOBBY A","race":"WHITE","sex":"MALE","dob":"2/16/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"108426","photo":"108426.jpg","name":"BELL, MICHAEL B","race":"BLACK","sex":"MALE","dob":"3/1/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"709795","photo":"709795.jpg","name":"ALSTON, PRESSLEY B","race":"BLACK","sex":"MALE","dob":"3/5/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"554000","photo":"554000.jpg","name":"ZAKRZEWSKI, EDWARD J II","race":"WHITE","sex":"MALE","dob":"4/19/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124283","photo":"124283.jpg","name":"POOLER, LEROY","race":"BLACK","sex":"MALE","dob":"4/30/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"P01395","photo":"P01395.jpg","name":"BROOKINS, ELIJAH J","race":"BLACK","sex":"MALE","dob":"6/17/96","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"286173","photo":"286173.jpg","name":"BELCHER, JAMES","race":"BLACK","sex":"MALE","dob":"9/6/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"86158","photo":"086158.jpg","name":"BOWLES, GARY R","race":"WHITE","sex":"MALE","dob":"9/9/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"721097","photo":"721097.jpg","name":"JENNINGS, BRANDY B","race":"WHITE","sex":"MALE","dob":"12/6/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"989102","photo":"989102.jpg","name":"NELSON, JOSHUA D","race":"WHITE","sex":"MALE","dob":"12/10/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"395352","photo":"395352.jpg","name":"GUZMAN, JAMES","race":"WHITE","sex":"MALE","dob":"12/27/96","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124346","photo":"124346.jpg","name":"TREASE, ROBERT J","race":"WHITE","sex":"MALE","dob":"1/23/97","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"122651","photo":"122651.jpg","name":"HOLLAND, ALBERT","race":"BLACK","sex":"MALE","dob":"2/13/97","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"375690","photo":"375690.jpg","name":"DOTY, WAYNE C","race":"WHITE","sex":"MALE","dob":"3/28/97","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"391485","photo":"391485.jpg","name":"LUKEHART, ANDREW R","race":"WHITE","sex":"MALE","dob":"4/4/97","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X06883","photo":"X06883.jpg","name":"SMITH, SEAN","race":"BLACK","sex":"MALE","dob":"4/18/97","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124400","photo":"124400.jpg","name":"ROGERS, GLEN E","race":"WHITE","sex":"MALE","dob":"7/11/97","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124439","photo":"124439.jpg","name":"ZACK, MICHAEL D III","race":"WHITE","sex":"MALE","dob":"12/5/97","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124460","photo":"124460.jpg","name":"MANSFIELD, SCOTT","race":"WHITE","sex":"MALE","dob":"2/2/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"71588","photo":"071588.jpg","name":"LAMARCA, ANTHONY","race":"WHITE","sex":"MALE","dob":"3/10/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124493","photo":"124493.jpg","name":"STEPHENS, JASON D","race":"BLACK","sex":"MALE","dob":"4/7/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"356054","photo":"356054.jpg","name":"BEASLEY, CURTIS W","race":"WHITE","sex":"MALE","dob":"6/3/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"66600","photo":"066600.jpg","name":"BRADLEY, DONALD L","race":"WHITE","sex":"MALE","dob":"6/29/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"406677","photo":"406677.jpg","name":"JIMENEZ, JOSE A","race":"WHITE","sex":"MALE","dob":"7/1/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"472846","photo":"472846.jpg","name":"LEBRON, JERMAINE","race":"BLACK","sex":"MALE","dob":"7/14/98","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Y01561","photo":"Y01561.jpg","name":"FOSTER, KEVIN D","race":"WHITE","sex":"MALE","dob":"7/22/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J08118","photo":"J08118.jpg","name":"MILLER, DAVID  JR.","race":"BLACK","sex":"MALE","dob":"7/24/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"M16320","photo":"M16320.jpg","name":"DOORBAL, NOEL","race":"WHITE","sex":"MALE","dob":"8/31/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"M16321","photo":"M16321.jpg","name":"LUGO, DANIEL","race":"WHITE","sex":"MALE","dob":"8/31/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124538","photo":"124538.jpg","name":"BROOKS, LAMAR Z","race":"BLACK","sex":"MALE","dob":"9/29/98","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"668630","photo":"668630.jpg","name":"PAGAN, ALEX","race":"WHITE","sex":"MALE","dob":"10/22/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"W08567","photo":"W08567.jpg","name":"FRANCIS, CARLTON A","race":"BLACK","sex":"MALE","dob":"11/17/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"113388","photo":"113388.jpg","name":"MORRISON, RAYMOND  JR.","race":"BLACK","sex":"MALE","dob":"12/21/98","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"233984","photo":"233984.jpg","name":"BUTLER, HARRY L","race":"BLACK","sex":"MALE","dob":"1/14/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"H06832","photo":"H06832.jpg","name":"WOODEL, THOMAS D","race":"WHITE","sex":"MALE","dob":"1/28/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124607","photo":"124607.jpg","name":"DENNIS, LABRANT D","race":"BLACK","sex":"MALE","dob":"3/25/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X18736","photo":"X18736.jpg","name":"JEFFRIES, SONNY R","race":"WHITE","sex":"MALE","dob":"4/14/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"550026","photo":"550026.jpg","name":"MORRIS, ROBERT D","race":"BLACK","sex":"MALE","dob":"5/4/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V01514","photo":"V01514.jpg","name":"FLOYD, MAURICE L","race":"BLACK","sex":"MALE","dob":"5/26/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"763722","photo":"763722.jpg","name":"FORD, JAMES D","race":"WHITE","sex":"MALE","dob":"6/11/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"572349","photo":"572349.jpg","name":"EVANS, PAUL H","race":"WHITE","sex":"MALE","dob":"6/17/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"911193","photo":"911193.jpg","name":"OVERTON, THOMAS M","race":"WHITE","sex":"MALE","dob":"7/13/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124639","photo":"124639.jpg","name":"SMITHERS, SAMUEL L","race":"WHITE","sex":"MALE","dob":"7/15/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"59121","photo":"059121.jpg","name":"HUGGINS, JOHN","race":"WHITE","sex":"MALE","dob":"8/5/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J12116","photo":"J12116.jpg","name":"TAYLOR, JOHN C II","race":"WHITE","sex":"MALE","dob":"10/8/99","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"145267","photo":"145267.jpg","name":"DAVIS, ADAM W","race":"WHITE","sex":"MALE","dob":"1/4/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Y02046","photo":"Y02046.jpg","name":"CONAHAN, DANIEL O JR.","race":"WHITE","sex":"MALE","dob":"1/10/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"567668","photo":"567668.jpg","name":"HERTZ, GUERRY W","race":"WHITE","sex":"MALE","dob":"2/24/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"N00676","photo":"N00676.jpg","name":"LOONEY, JASON B","race":"WHITE","sex":"MALE","dob":"2/24/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"113416","photo":"113416.jpg","name":"EVANS, WYDELL J","race":"BLACK","sex":"MALE","dob":"3/8/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"664697","photo":"664697.jpg","name":"AULT, HOWARD S","race":"WHITE","sex":"MALE","dob":"3/15/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"535168","photo":"535168.jpg","name":"NELSON, MICAH L","race":"BLACK","sex":"MALE","dob":"3/22/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V02093","photo":"V02093.jpg","name":"BROWN, PAUL A","race":"WHITE","sex":"MALE","dob":"4/19/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124669","photo":"124669.jpg","name":"HURST, TIMOTHY L","race":"BLACK","sex":"MALE","dob":"5/2/00","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"347463","photo":"347463.jpg","name":"SPANN, ANTHONY A","race":"BLACK","sex":"MALE","dob":"7/13/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"898522","photo":"898522.jpg","name":"LAWRENCE, JONATHAN H","race":"WHITE","sex":"MALE","dob":"8/16/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"314648","photo":"314648.jpg","name":"PHILMORE, LENARD J","race":"BLACK","sex":"MALE","dob":"8/21/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"96344","photo":"096344.jpg","name":"CRAIN, WILLIE S JR.","race":"WHITE","sex":"MALE","dob":"9/14/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"123101","photo":"123101.jpg","name":"RODGERS, JEREMIAH M","race":"WHITE","sex":"MALE","dob":"11/22/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"282008","photo":"282008.jpg","name":"GRIM, NORMAN M","race":"WHITE","sex":"MALE","dob":"12/22/00","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"218693","photo":"218693.jpg","name":"ANDERSON, FRED  JR.","race":"BLACK","sex":"MALE","dob":"1/12/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"166224","photo":"166224.jpg","name":"EAGLIN, DWIGHT T","race":"WHITE","sex":"MALE","dob":"1/23/01","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Y06133","photo":"Y06133.jpg","name":"DIAZ, JOEL","race":"HISPANIC","sex":"MALE","dob":"2/5/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"124849","photo":"124849.jpg","name":"HUTCHINSON, JEFFREY G","race":"WHITE","sex":"MALE","dob":"2/7/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"E08942","photo":"E08942.jpg","name":"LYNCH, RICHARD E","race":"WHITE","sex":"MALE","dob":"4/5/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"M25274","photo":"M25274.jpg","name":"CONDE, RORY E","race":"WHITE","sex":"MALE","dob":"7/12/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"105559","photo":"105559.jpg","name":"GILL, RICARDO I","race":"WHITE","sex":"MALE","dob":"7/20/01","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"927442","photo":"927442.jpg","name":"JOHNSTON, RAY L","race":"WHITE","sex":"MALE","dob":"8/24/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"R05023","photo":"R05023.jpg","name":"DESSAURE, KENNETH L JR","race":"BLACK","sex":"MALE","dob":"11/6/01","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"T28329","photo":"T28329.jpg","name":"HERNANDEZ-ALBERTO, PEDRO","race":"WHITE","sex":"MALE","dob":"6/10/02","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"H10118","photo":"H10118.jpg","name":"WRIGHT, TAVARES J","race":"BLACK","sex":"MALE","dob":"6/14/02","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"442564","photo":"442564.jpg","name":"SNELGROVE, DAVID B","race":"WHITE","sex":"MALE","dob":"6/14/02","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"125172","photo":"125172.jpg","name":"DOUGLAS, LUTHER","race":"BLACK","sex":"MALE","dob":"6/14/02","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"699893","photo":"699893.jpg","name":"BOYD, LUCIOUS","race":"BLACK","sex":"MALE","dob":"6/25/02","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Q13157","photo":"Q13157.jpg","name":"EVERETT, PAUL G","race":"WHITE","sex":"MALE","dob":"1/13/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"R30302","photo":"R30302.jpg","name":"FLOYD, FRANKLIN D","race":"WHITE","sex":"MALE","dob":"2/24/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"K04389","photo":"K04389.jpg","name":"TANZI, MICHAEL A","race":"WHITE","sex":"MALE","dob":"4/11/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"105669","photo":"105669.jpg","name":"SEIBERT, MICHAEL D","race":"WHITE","sex":"MALE","dob":"4/17/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"291140","photo":"291140.jpg","name":"MURRAY, GERALD D","race":"WHITE","sex":"MALE","dob":"6/26/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"324170","photo":"324170.jpg","name":"REYNOLDS, MICHAEL G","race":"WHITE","sex":"MALE","dob":"9/22/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"E20773","photo":"E20773.jpg","name":"SCHOENWETTER, RANDY L","race":"WHITE","sex":"MALE","dob":"12/9/03","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"121605","photo":"121605.jpg","name":"TROY, JOHN","race":"WHITE","sex":"MALE","dob":"2/4/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"E11617","photo":"E11617.jpg","name":"BUZIA, JOHN M","race":"WHITE","sex":"MALE","dob":"3/12/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"645118","photo":"645118.jpg","name":"WILLIAMS, RONNIE K","race":"BLACK","sex":"MALE","dob":"4/23/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"10243","photo":"010243.jpg","name":"RODGERS, THEODORE  JR","race":"BLACK","sex":"MALE","dob":"6/23/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"115574","photo":"115574.jpg","name":"ENGLAND, RICHARD","race":"HISPANIC","sex":"MALE","dob":"7/23/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"K51342","photo":"K51342.jpg","name":"JOHNSON, RICHARD A","race":"WHITE","sex":"MALE","dob":"8/12/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"111640","photo":"111640.jpg","name":"TAYLOR, WILLIAM K","race":"WHITE","sex":"MALE","dob":"10/7/04","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X33939","photo":"X33939.jpg","name":"FRANCES, DAVID","race":"BLACK","sex":"MALE","dob":"5/13/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"192202","photo":"192202.jpg","name":"SMITH, COREY","race":"BLACK","sex":"MALE","dob":"6/30/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"L49959","photo":"L49959.jpg","name":"HOJAN, GERHARD","race":"WHITE","sex":"MALE","dob":"8/4/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"H12548","photo":"H12548.jpg","name":"POOLE, MARK A","race":"BLACK","sex":"MALE","dob":"8/29/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"H23012","photo":"H23012.jpg","name":"RIGTERINK, THOMAS W","race":"WHITE","sex":"MALE","dob":"10/18/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J29642","photo":"J29642.jpg","name":"BEVEL, THOMAS E","race":"BLACK","sex":"MALE","dob":"10/24/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"127513","photo":"127513.jpg","name":"CARTER, PINKNEY W","race":"WHITE","sex":"MALE","dob":"12/27/05","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"899500","photo":"899500.jpg","name":"SMITH, JOSEPH P","race":"WHITE","sex":"MALE","dob":"3/20/06","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"128019","photo":"128019.jpg","name":"SALAZAR, NEIL K","race":"BLACK","sex":"MALE","dob":"6/14/06","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J30192","photo":"J30192.jpg","name":"MOSLEY, JOHN F","race":"BLACK","sex":"MALE","dob":"7/3/06","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"128135","photo":"128135.jpg","name":"BAILEY, ROBERT J","race":"WHITE","sex":"MALE","dob":"7/24/06","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"898405.jpg","photo":"898405","name":"VICTORINO, TROY","race":"HISPANIC","sex":"MALE","dob":"9/22/06","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V26165","photo":"V26166.jpg","name":"HUNTER, JERONE","race":"BLACK","sex":"MALE","dob":"9/22/06","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"991988","photo":"991988.jpg","name":"WHEELER, JASON L","race":"WHITE","sex":"MALE","dob":"10/24/06","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"P31867","photo":"P31867.jpg","name":"HERNANDEZ, MICHAEL A JR","race":"WHITE","sex":"MALE","dob":"3/23/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"L36345.jpg","photo":"L36346.jpg","name":"KNIGHT, RICHARD","race":"BLACK","sex":"MALE","dob":"3/30/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"301898","photo":"301898.jpg","name":"SIMPSON, JASON A","race":"WHITE","sex":"MALE","dob":"3/30/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"106576","photo":"106576.jpg","name":"HAYWARD, STEVEN D","race":"BLACK","sex":"MALE","dob":"6/4/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"973885","photo":"973885.jpg","name":"JACKSON, RAY","race":"BLACK","sex":"MALE","dob":"6/22/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"129232","photo":"129232.jpg","name":"SERRANO, NELSON I","race":"WHITE","sex":"MALE","dob":"6/28/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Y32888","photo":"Y32888.jpg","name":"TWILEGAR, MARK A","race":"WHITE","sex":"MALE","dob":"8/16/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J34141","photo":"J34141.jpg","name":"JACKSON, MICHAEL","race":"WHITE","sex":"MALE","dob":"8/30/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"406356","photo":"406356.jpg","name":"BRADDY, HARREL F","race":"BLACK","sex":"MALE","dob":"10/18/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"996584","photo":"996584.jpg","name":"MCLEAN, DERRICK","race":"BLACK","sex":"MALE","dob":"12/6/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"588873","photo":"588873.jpg","name":"BRANT, CHARLES G","race":"WHITE","sex":"MALE","dob":"12/6/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J19087","photo":"J19087.jpg","name":"DUROUSSEAU, PAUL","race":"BLACK","sex":"MALE","dob":"12/14/07","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"25171","photo":"025171.jpg","name":"MILLER, LIONEL","race":"WHITE","sex":"MALE","dob":"2/7/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"349878","photo":"349878.jpg","name":"ZOMMER, TODD","race":"WHITE","sex":"MALE","dob":"2/26/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J35401","photo":"J35401.jpg","name":"WADE, ALAN","race":"WHITE","sex":"MALE","dob":"3/5/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J35212","photo":"J35212.jpg","name":"COLE, TIFFANY","race":"WHITE","sex":"FEMALE","dob":"3/7/08","entry":"LOWELL ANNEX","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V29754","photo":"V29754.jpg","name":"TURNER, JAMES D","race":"WHITE","sex":"MALE","dob":"4/25/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"U33164","photo":"U33164.jpg","name":"MCGIRTH, RENALDO D","race":"BLACK","sex":"MALE","dob":"5/6/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"130335","photo":"130335.jpg","name":"ABDOOL, DANE","race":"WHITE","sex":"MALE","dob":"5/19/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J29603","photo":"J29603.jpg","name":"BANKS, DONALD L","race":"BLACK","sex":"MALE","dob":"8/18/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J03479","photo":"J03479.jpg","name":"PHILLIPS, GALANTE R","race":"BLACK","sex":"MALE","dob":"9/22/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"165328","photo":"165328.jpg","name":"KIRKMAN, VAHTEICE A","race":"BLACK","sex":"MALE","dob":"10/1/08","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"953712","photo":"953712.jpg","name":"PHAM, TAI A","race":"WHITE","sex":"MALE","dob":"11/17/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"130930","photo":"130930.jpg","name":"ALLRED, ANDREW R","race":"WHITE","sex":"MALE","dob":"11/21/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"185563","photo":"185563.jpg","name":"PARTIN, PHILLUP A","race":"WHITE","sex":"MALE","dob":"12/2/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J01369","photo":"J01369.jpg","name":"MCCRAY, GARY B","race":"BLACK","sex":"MALE","dob":"12/11/08","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"P36814","photo":"P36814.jpg","name":"HODGES, WILLIE J","race":"BLACK","sex":"MALE","dob":"2/18/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V25581","photo":"V25581.jpg","name":"BAKER, CORNELIUS O","race":"BLACK","sex":"MALE","dob":"3/5/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V14470","photo":"V14470.jpg","name":"FLETCHER, TIMOTHY W","race":"WHITE","sex":"MALE","dob":"4/21/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"358986","photo":"358986.jpg","name":"RUSS, DAVID B","race":"WHITE","sex":"MALE","dob":"5/14/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"131596","photo":"131596.jpg","name":"ALTERSBERGER, JOSHUA L","race":"BLACK","sex":"MALE","dob":"6/17/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"197598","photo":"197598.jpg","name":"PATRICK, ERIC K","race":"WHITE","sex":"MALE","dob":"10/21/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"K54395","photo":"K54395.jpg","name":"GOSCIMINSKI, ANDREW M","race":"WHITE","sex":"MALE","dob":"11/13/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"200047","photo":"200047.jpg","name":"BRIGHT, RAYMOND","race":"BLACK","sex":"MALE","dob":"11/20/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X45131","photo":"X45131.jpg","name":"HALL, DONTE J","race":"BLACK","sex":"MALE","dob":"12/10/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"287224","photo":"287224.jpg","name":"PETERSON, ROBERT E","race":"WHITE","sex":"MALE","dob":"12/14/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"132254","photo":"132254.jpg","name":"KING, MICHAEL L","race":"WHITE","sex":"MALE","dob":"12/14/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Q23494","photo":"Q23494.jpg","name":"CAYLOR, MATTHEW L","race":"WHITE","sex":"MALE","dob":"12/15/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X23653","photo":"X23653.jpg","name":"HEYNE, JUSTIN C","race":"WHITE","sex":"MALE","dob":"12/18/09","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X50469","photo":"X50469.jpg","name":"ELLERBEE, TERRY M JR.","race":"WHITE","sex":"MALE","dob":"2/2/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"479701","photo":"479701.jpg","name":"KOCAKER, GENGHIS N","race":"WHITE","sex":"MALE","dob":"2/2/10","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"132474","photo":"132474.jpg","name":"HAMPTON, JOHN L","race":"BLACK","sex":"MALE","dob":"2/23/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J30258","photo":"J30258.jpg","name":"MARTIN, DAVID J","race":"WHITE","sex":"MALE","dob":"3/18/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J40507","photo":"J40507.jpg","name":"SANCHEZ-TORREZ, HECTOR G","race":"HISPANIC","sex":"MALE","dob":"4/8/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V29877","photo":"V29877.jpg","name":"MATTHEWS, DOUGLAS B","race":"BLACK","sex":"MALE","dob":"8/13/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"133220","photo":"133220.jpg","name":"MCMILLIAN, JUSTIN","race":"BLACK","sex":"MALE","dob":"10/7/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"M03128","photo":"M03128.jpg","name":"CALLOWAY, TAVARES D","race":"BLACK","sex":"MALE","dob":"10/26/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"R17262","photo":"R17262.jpg","name":"ROBARDS, RICHARD T","race":"WHITE","sex":"MALE","dob":"11/9/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J20499","photo":"J20499.jpg","name":"KACZMAR, LEO L III","race":"WHITE","sex":"MALE","dob":"11/15/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"D40377","photo":"D40377.jpg","name":"MCCOY, THOMAS F","race":"WHITE","sex":"MALE","dob":"11/19/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"133428","photo":"133428.jpg","name":"DUBOSE, RASHEEM","race":"BLACK","sex":"MALE","dob":"12/14/10","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"768915","photo":"768915.jpg","name":"GONZALEZ, LEONARD P JR","race":"WHITE","sex":"MALE","dob":"2/18/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"U24131","photo":"U24131.jpg","name":"CARR, EMILIA L","race":"HISPANIC","sex":"FEMALE","dob":"2/23/11","entry":"LOWELL ANNEX","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"V19522","photo":"V19522.jpg","name":"GREGORY, WILLIAM A","race":"WHITE","sex":"MALE","dob":"4/15/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"133897","photo":"133897.jpg","name":"HILTON, GARY M","race":"WHITE","sex":"MALE","dob":"4/22/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"H27248","photo":"H27248.jpg","name":"DAVIS, LEON  JR","race":"BLACK","sex":"MALE","dob":"5/5/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"444904","photo":"444904.jpg","name":"WILCOX, DARIOUS","race":"BLACK","sex":"MALE","dob":"5/19/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"699575","photo":"699575.jpg","name":"ALLEN, MARGARET A","race":"BLACK","sex":"FEMALE","dob":"5/19/11","entry":"LOWELL ANNEX","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J44119","photo":"J44119.jpg","name":"JEAN-PHILIPPE, LESLY","race":"BLACK","sex":"MALE","dob":"6/6/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"130985","photo":"130985.jpg","name":"SMITH, TERRY","race":"BLACK","sex":"MALE","dob":"6/10/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"120774","photo":"120774.jpg","name":"NEWBERRY, RODNEY R","race":"BLACK","sex":"MALE","dob":"7/28/11","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"L88290","photo":"L88290.jpg","name":"HERARD, JAMES","race":"BLACK","sex":"MALE","dob":"9/8/11","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"D30662","photo":"D30662.jpg","name":"BROWN, THOMAS T","race":"BLACK","sex":"MALE","dob":"10/31/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J25731","photo":"J25731.jpg","name":"KING, CECIL S","race":"BLACK","sex":"MALE","dob":"10/31/11","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"D35843","photo":"D35843.jpg","name":"CAMPBELL, JOHN W","race":"WHITE","sex":"MALE","dob":"12/30/11","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"U44139","photo":"U44139.jpg","name":"MARQUARDT, BILL P","race":"WHITE","sex":"MALE","dob":"3/15/12","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J46231","photo":"J46231.jpg","name":"SPARRE, DAVID K","race":"WHITE","sex":"MALE","dob":"4/2/12","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"J18546","photo":"J18546.jpg","name":"SHEPPARD, BILLY J JR","race":"BLACK","sex":"MALE","dob":"4/2/12","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Q26629","photo":"Q26629.jpg","name":"CALHOUN, JOHNNY M","race":"WHITE","sex":"MALE","dob":"5/23/12","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"977097","photo":"977097.jpg","name":"OLIVER, TERENCE T","race":"BLACK","sex":"MALE","dob":"6/18/12","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"436687","photo":"436687.jpg","name":"MARTIN, ARTHUR","race":"BLACK","sex":"MALE","dob":"8/6/12","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"155917","photo":"155917.jpg","name":"BROWN, TINA L","race":"BLACK","sex":"FEMALE","dob":"10/3/12","entry":"LOWELL ANNEX","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"801152","photo":"801152.jpg","name":"MIDDLETON, DALE","race":"WHITE","sex":"MALE","dob":"10/25/12","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"N08206","photo":"N08206.jpg","name":"CANNON, MARVIN","race":"BLACK","sex":"MALE","dob":"11/19/12","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"752320","photo":"752320.jpg","name":"HOBART, ROBERT L","race":"WHITE","sex":"MALE","dob":"12/3/12","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"H17413","photo":"H17413.jpg","name":"DAVIS, WILLIAM R III","race":"WHITE","sex":"MALE","dob":"12/18/12","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"135556","photo":"135556.jpg","name":"LEBRON, JOEL G","race":"BLACK","sex":"MALE","dob":"3/26/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X40969","photo":"X40969.jpg","name":"GUZMAN, VICTOR","race":"WHITE","sex":"MALE","dob":"5/21/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"Q09582","photo":"Q09582.jpg","name":"JACKSON, KENNETH R","race":"WHITE","sex":"MALE","dob":"6/5/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"135769","photo":"135769.jpg","name":"SMITH, DELMER  III","race":"WHITE","sex":"MALE","dob":"7/1/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"T58435","photo":"T58435.jpg","name":"PASHA, KHALID A","race":"BLACK","sex":"MALE","dob":"8/5/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"R17884","photo":"R17884.jpg","name":"MULLENS, KHADAFY","race":"BLACK","sex":"MALE","dob":"8/27/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"180632","photo":"180632.jpg","name":"JORDAN, JOSEPH E","race":"WHITE","sex":"MALE","dob":"9/25/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"135963","photo":"135963.jpg","name":"JACKSON, KIM","race":"BLACK","sex":"MALE","dob":"10/2/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"X46345","photo":"X46345.jpg","name":"OKAFOR, BESSMAN O","race":"BLACK","sex":"MALE","dob":"10/18/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"135997","photo":"135997.jpg","name":"COZZIE, STEVEN A","race":"WHITE","sex":"MALE","dob":"10/18/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"U21898","photo":"U21898.jpg","name":"SEXTON, JOHN  JR","race":"WHITE","sex":"MALE","dob":"12/16/13","entry":"FLORIDA STATE PRISON","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"U41472","photo":"U41472.jpg","name":"BARGO, MICHAEL S JR","race":"WHITE","sex":"MALE","dob":"12/16/13","entry":"UNION C.I.","facility":"MAXIMUM","custody":"DEATH SENTENCE"},
{"id":"U13479","photo":"U13479.jpg","name":"WILLIAMS, DONALD O","race":"WHITE","sex":"MALE","dob":"3/3/14","entry":"OUT OF DEPT. CUSTODY BY COURT ORDER","facility":"MAXIMUM","custody":"DEATH SENTENCE"}];